// HSK 1-3 Vocab — Монгол тайлбартай (553 үг)
const HSK_VOCAB_ALL = [{"word":"爱","pinyin":"ài","definition":"хайрлах, дурлах","en":"хайрлах, дурлах","hsk_level":1},
{"word":"八","pinyin":"bā","definition":"найм","en":"найм","hsk_level":1},
{"word":"爸爸","pinyin":"bàba","definition":"аав","en":"аав","hsk_level":1},
{"word":"杯子","pinyin":"bēizi","definition":"аяга","en":"аяга","hsk_level":1},
{"word":"北京","pinyin":"Běijīng","definition":"Бээжин","en":"Бээжин","hsk_level":1},
{"word":"本","pinyin":"běn","definition":"ширхэг (ном, дэвтэр тоолох үг)","en":"ширхэг (ном, дэвтэр тоолох үг)","hsk_level":1},
{"word":"不客气","pinyin":"bú kèqi","definition":"зүгээр дээ","en":"зүгээр дээ","hsk_level":1},
{"word":"不","pinyin":"bù","definition":"үгүй, биш","en":"үгүй, биш","hsk_level":1},
{"word":"菜","pinyin":"cài","definition":"хоол, ногоо","en":"хоол, ногоо","hsk_level":1},
{"word":"茶","pinyin":"chá","definition":"цай","en":"цай","hsk_level":1},
{"word":"吃","pinyin":"chī","definition":"идэх","en":"идэх","hsk_level":1},
{"word":"出租车","pinyin":"chūzūchē","definition":"такси","en":"такси","hsk_level":1},
{"word":"打电话","pinyin":"dǎ diànhuà","definition":"утсаар ярих","en":"утсаар ярих","hsk_level":1},
{"word":"大","pinyin":"dà","definition":"том","en":"том","hsk_level":1},
{"word":"的","pinyin":"de","definition":"харьяалах нөхцөл (-ын/-ий)","en":"харьяалах нөхцөл (-ын/-ий)","hsk_level":1},
{"word":"点","pinyin":"diǎn","definition":"цэг, цаг, жаахан","en":"цэг, цаг, жаахан","hsk_level":1},
{"word":"电脑","pinyin":"diànnǎo","definition":"компьютер","en":"компьютер","hsk_level":1},
{"word":"电视","pinyin":"diànshì","definition":"зурагт, телевиз","en":"зурагт, телевиз","hsk_level":1},
{"word":"电影","pinyin":"diànyǐng","definition":"кино","en":"кино","hsk_level":1},
{"word":"东西","pinyin":"dōngxi","definition":"юм, эд зүйл","en":"юм, эд зүйл","hsk_level":1},
{"word":"都","pinyin":"dōu","definition":"бүгд, цөм","en":"бүгд, цөм","hsk_level":1},
{"word":"读","pinyin":"dú","definition":"унших, сурах","en":"унших, сурах","hsk_level":1},
{"word":"对不起","pinyin":"duìbuqǐ","definition":"уучлаарай","en":"уучлаарай","hsk_level":1},
{"word":"多","pinyin":"duō","definition":"олон, их","en":"олон, их","hsk_level":1},
{"word":"多少","pinyin":"duōshao","definition":"хэд, хэдий","en":"хэд, хэдий","hsk_level":1},
{"word":"儿子","pinyin":"érzi","definition":"хүү","en":"хүү","hsk_level":1},
{"word":"二","pinyin":"èr","definition":"хоёр","en":"хоёр","hsk_level":1},
{"word":"饭店","pinyin":"fàndiàn","definition":"зоогийн газар, зочид буудал","en":"зоогийн газар, зочид буудал","hsk_level":1},
{"word":"飞机","pinyin":"fēijī","definition":"онгоц","en":"онгоц","hsk_level":1},
{"word":"分钟","pinyin":"fēnzhōng","definition":"минут","en":"минут","hsk_level":1},
{"word":"高兴","pinyin":"gāoxìng","definition":"баяртай, баясах","en":"баяртай, баясах","hsk_level":1},
{"word":"个","pinyin":"ge","definition":"ширхэг (ерөнхий тоолох үг)","en":"ширхэг (ерөнхий тоолох үг)","hsk_level":1},
{"word":"工作","pinyin":"gōngzuò","definition":"ажил, ажиллах","en":"ажил, ажиллах","hsk_level":1},
{"word":"狗","pinyin":"gǒu","definition":"нохой","en":"нохой","hsk_level":1},
{"word":"汉语","pinyin":"Hànyǔ","definition":"Хятад хэл","en":"Хятад хэл","hsk_level":1},
{"word":"好","pinyin":"hǎo","definition":"сайн","en":"сайн","hsk_level":1},
{"word":"号","pinyin":"hào","definition":"дугаар, өдөр","en":"дугаар, өдөр","hsk_level":1},
{"word":"喝","pinyin":"hē","definition":"уух","en":"уух","hsk_level":1},
{"word":"和","pinyin":"hé","definition":"ба, -той хамт","en":"ба, -той хамт","hsk_level":1},
{"word":"很","pinyin":"hěn","definition":"маш, их","en":"маш, их","hsk_level":1},
{"word":"后面","pinyin":"hòumian","definition":"ар тал, ард","en":"ар тал, ард","hsk_level":1},
{"word":"回","pinyin":"huí","definition":"буцах, хариулах","en":"буцах, хариулах","hsk_level":1},
{"word":"会","pinyin":"huì","definition":"чадах, мэдэх","en":"чадах, мэдэх","hsk_level":1},
{"word":"几","pinyin":"jǐ","definition":"хэд, цөөхөн","en":"хэд, цөөхөн","hsk_level":1},
{"word":"家","pinyin":"jiā","definition":"гэр, гэр бүл","en":"гэр, гэр бүл","hsk_level":1},
{"word":"叫","pinyin":"jiào","definition":"дуудах, нэрлэх","en":"дуудах, нэрлэх","hsk_level":1},
{"word":"今天","pinyin":"jīntiān","definition":"өнөөдөр","en":"өнөөдөр","hsk_level":1},
{"word":"九","pinyin":"jiǔ","definition":"ес","en":"ес","hsk_level":1},
{"word":"开","pinyin":"kāi","definition":"нээх, асаах, жолоодох","en":"нээх, асаах, жолоодох","hsk_level":1},
{"word":"看","pinyin":"kàn","definition":"харах, үзэх","en":"харах, үзэх","hsk_level":1},
{"word":"看见","pinyin":"kànjiàn","definition":"олж харах","en":"олж харах","hsk_level":1},
{"word":"块","pinyin":"kuài","definition":"зүсэм, юань","en":"зүсэм, юань","hsk_level":1},
{"word":"来","pinyin":"lái","definition":"ирэх","en":"ирэх","hsk_level":1},
{"word":"老师","pinyin":"lǎoshī","definition":"багш","en":"багш","hsk_level":1},
{"word":"了","pinyin":"le","definition":"үйл үгийн дуусгавар нөхцөл","en":"үйл үгийн дуусгавар нөхцөл","hsk_level":1},
{"word":"冷","pinyin":"lěng","definition":"хүйтэн","en":"хүйтэн","hsk_level":1},
{"word":"里","pinyin":"lǐ","definition":"дотор","en":"дотор","hsk_level":1},
{"word":"六","pinyin":"liù","definition":"зургаа","en":"зургаа","hsk_level":1},
{"word":"妈妈","pinyin":"māma","definition":"ээж","en":"ээж","hsk_level":1},
{"word":"吗","pinyin":"ma","definition":"уу, үү (асуух сул үг)","en":"уу, үү (асуух сул үг)","hsk_level":1},
{"word":"买","pinyin":"mǎi","definition":"худалдаж авах","en":"худалдаж авах","hsk_level":1},
{"word":"猫","pinyin":"māo","definition":"муур","en":"муур","hsk_level":1},
{"word":"没关系","pinyin":"méi guānxi","definition":"зүгээр, хамаагүй","en":"зүгээр, хамаагүй","hsk_level":1},
{"word":"没有","pinyin":"méiyǒu","definition":"байхгүй","en":"байхгүй","hsk_level":1},
{"word":"米饭","pinyin":"mǐfàn","definition":"цагаан будаа","en":"цагаан будаа","hsk_level":1},
{"word":"明天","pinyin":"míngtiān","definition":"маргааш","en":"маргааш","hsk_level":1},
{"word":"名字","pinyin":"míngzi","definition":"нэр","en":"нэр","hsk_level":1},
{"word":"哪","pinyin":"nǎ","definition":"аль","en":"аль","hsk_level":1},
{"word":"哪儿","pinyin":"nǎr","definition":"хаана","en":"хаана","hsk_level":1},
{"word":"那","pinyin":"nà","definition":"тэр","en":"тэр","hsk_level":1},
{"word":"呢","pinyin":"ne","definition":"харин, -ч (асуух сул үг)","en":"харин, -ч (асуух сул үг)","hsk_level":1},
{"word":"能","pinyin":"néng","definition":"чадах","en":"чадах","hsk_level":1},
{"word":"你","pinyin":"nǐ","definition":"чи","en":"чи","hsk_level":1},
{"word":"年","pinyin":"nián","definition":"жил","en":"жил","hsk_level":1},
{"word":"女儿","pinyin":"nǚér","definition":"охин","en":"охин","hsk_level":1},
{"word":"朋友","pinyin":"péngyou","definition":"найз","en":"найз","hsk_level":1},
{"word":"漂亮","pinyin":"piàoliang","definition":"хөөрхөн, үзэсгэлэнтэй","en":"хөөрхөн, үзэсгэлэнтэй","hsk_level":1},
{"word":"苹果","pinyin":"píngguǒ","definition":"алим","en":"алим","hsk_level":1},
{"word":"七","pinyin":"qī","definition":"долоо","en":"долоо","hsk_level":1},
{"word":"钱","pinyin":"qián","definition":"мөнгө","en":"мөнгө","hsk_level":1},
{"word":"前面","pinyin":"qiánmiàn","definition":"урд тал, өмнө","en":"урд тал, өмнө","hsk_level":1},
{"word":"请","pinyin":"qǐng","definition":"гуйх, урих","en":"гуйх, урих","hsk_level":1},
{"word":"去","pinyin":"qù","definition":"явах","en":"явах","hsk_level":1},
{"word":"热","pinyin":"rè","definition":"халуун","en":"халуун","hsk_level":1},
{"word":"人","pinyin":"rén","definition":"хүн","en":"хүн","hsk_level":1},
{"word":"认识","pinyin":"rènshi","definition":"таних, танилцах","en":"таних, танилцах","hsk_level":1},
{"word":"三","pinyin":"sān","definition":"гурав","en":"гурав","hsk_level":1},
{"word":"商店","pinyin":"shāngdiàn","definition":"дэлгүүр","en":"дэлгүүр","hsk_level":1},
{"word":"上","pinyin":"shàng","definition":"дээр, гарах","en":"дээр, гарах","hsk_level":1},
{"word":"上午","pinyin":"shàngwǔ","definition":"өглөө","en":"өглөө","hsk_level":1},
{"word":"少","pinyin":"shǎo","definition":"цөөн, бага","en":"цөөн, бага","hsk_level":1},
{"word":"谁","pinyin":"shéi","definition":"хэн","en":"хэн","hsk_level":1},
{"word":"什么","pinyin":"shénme","definition":"юу","en":"юу","hsk_level":1},
{"word":"十","pinyin":"shí","definition":"арав","en":"арав","hsk_level":1},
{"word":"时候","pinyin":"shíhou","definition":"цаг, үе","en":"цаг, үе","hsk_level":1},
{"word":"是","pinyin":"shì","definition":"мөн, байх, тийм","en":"мөн, байх, тийм","hsk_level":1},
{"word":"书","pinyin":"shū","definition":"ном","en":"ном","hsk_level":1},
{"word":"水","pinyin":"shuǐ","definition":"ус","en":"ус","hsk_level":1},
{"word":"水果","pinyin":"shuǐguǒ","definition":"жимс","en":"жимс","hsk_level":1},
{"word":"睡觉","pinyin":"shuì jiào","definition":"унтах","en":"унтах","hsk_level":1},
{"word":"说","pinyin":"shuō","definition":"ярих, хэлэх","en":"ярих, хэлэх","hsk_level":1},
{"word":"四","pinyin":"sì","definition":"дөрөв","en":"дөрөв","hsk_level":1},
{"word":"岁","pinyin":"suì","definition":"нас","en":"нас","hsk_level":1},
{"word":"他","pinyin":"tā","definition":"тэр (эрэгтэй)","en":"тэр (эрэгтэй)","hsk_level":1},
{"word":"她","pinyin":"tā","definition":"тэр (эмэгтэй)","en":"тэр (эмэгтэй)","hsk_level":1},
{"word":"太","pinyin":"tài","definition":"хэтэрхий","en":"хэтэрхий","hsk_level":1},
{"word":"天气","pinyin":"tiānqì","definition":"цаг агаар","en":"цаг агаар","hsk_level":1},
{"word":"听","pinyin":"tīng","definition":"сонсох","en":"сонсох","hsk_level":1},
{"word":"同学","pinyin":"tóngxué","definition":"ангийн найз","en":"ангийн найз","hsk_level":1},
{"word":"喂","pinyin":"wèi","definition":"байна уу (утсаар)","en":"байна уу (утсаар)","hsk_level":1},
{"word":"我","pinyin":"wǒ","definition":"би","en":"би","hsk_level":1},
{"word":"我们","pinyin":"wǒmen","definition":"бид","en":"бид","hsk_level":1},
{"word":"五","pinyin":"wǔ","definition":"тав","en":"тав","hsk_level":1},
{"word":"喜欢","pinyin":"xǐhuan","definition":"дуртай байх","en":"дуртай байх","hsk_level":1},
{"word":"下","pinyin":"xià","definition":"доор, буурах","en":"доор, буурах","hsk_level":1},
{"word":"下午","pinyin":"xiàwǔ","definition":"үдээс хойш","en":"үдээс хойш","hsk_level":1},
{"word":"下雨","pinyin":"xiàyǔ","definition":"бороо орох","en":"бороо орох","hsk_level":1},
{"word":"先生","pinyin":"xiānsheng","definition":"ноён","en":"ноён","hsk_level":1},
{"word":"现在","pinyin":"xiànzài","definition":"одоо","en":"одоо","hsk_level":1},
{"word":"想","pinyin":"xiǎng","definition":"бодох, хүсэх","en":"бодох, хүсэх","hsk_level":1},
{"word":"小","pinyin":"xiǎo","definition":"жижиг, бага","en":"жижиг, бага","hsk_level":1},
{"word":"小姐","pinyin":"xiǎojie","definition":"бүсгүй","en":"бүсгүй","hsk_level":1},
{"word":"些","pinyin":"xiē","definition":"зарим, хэдэн","en":"зарим, хэдэн","hsk_level":1},
{"word":"写","pinyin":"xiě","definition":"бичих","en":"бичих","hsk_level":1},
{"word":"谢谢","pinyin":"xièxie","definition":"баярлалаа","en":"баярлалаа","hsk_level":1},
{"word":"星期","pinyin":"xīngqī","definition":"долоо хоног, гараг","en":"долоо хоног, гараг","hsk_level":1},
{"word":"学生","pinyin":"xuésheng","definition":"сурагч, оюутан","en":"сурагч, оюутан","hsk_level":1},
{"word":"学习","pinyin":"xuéxí","definition":"сурах, судлах","en":"сурах, судлах","hsk_level":1},
{"word":"学校","pinyin":"xuéxiào","definition":"сургууль","en":"сургууль","hsk_level":1},
{"word":"一","pinyin":"yī","definition":"нэг","en":"нэг","hsk_level":1},
{"word":"衣服","pinyin":"yīfu","definition":"хувцас","en":"хувцас","hsk_level":1},
{"word":"医生","pinyin":"yīshēng","definition":"эмч","en":"эмч","hsk_level":1},
{"word":"医院","pinyin":"yīyuàn","definition":"эмнэлэг","en":"эмнэлэг","hsk_level":1},
{"word":"椅子","pinyin":"yǐzi","definition":"сандал","en":"сандал","hsk_level":1},
{"word":"一点儿","pinyin":"yìdiǎnr","definition":"жаахан, бага зэрэг","en":"жаахан, бага зэрэг","hsk_level":1},
{"word":"有","pinyin":"yǒu","definition":"байх, бий","en":"байх, бий","hsk_level":1},
{"word":"月","pinyin":"yuè","definition":"сар","en":"сар","hsk_level":1},
{"word":"在","pinyin":"zài","definition":"-д/-т байх","en":"-д/-т байх","hsk_level":1},
{"word":"再见","pinyin":"zàijiàn","definition":"баяртай","en":"баяртай","hsk_level":1},
{"word":"怎么","pinyin":"zěnme","definition":"яаж, хэрхэн","en":"яаж, хэрхэн","hsk_level":1},
{"word":"怎么样","pinyin":"zěnmeyàng","definition":"ямар байна","en":"ямар байна","hsk_level":1},
{"word":"这","pinyin":"zhè","definition":"энэ","en":"энэ","hsk_level":1},
{"word":"中国","pinyin":"Zhōngguó","definition":"Хятад улс","en":"Хятад улс","hsk_level":1},
{"word":"中午","pinyin":"zhōngwǔ","definition":"үд дунд","en":"үд дунд","hsk_level":1},
{"word":"住","pinyin":"zhù","definition":"суух, амьдрах","en":"суух, амьдрах","hsk_level":1},
{"word":"桌子","pinyin":"zhuōzi","definition":"ширээ","en":"ширээ","hsk_level":1},
{"word":"字","pinyin":"zì","definition":"үсэг, ханз","en":"үсэг, ханз","hsk_level":1},
{"word":"昨天","pinyin":"zuótiān","definition":"өчигдөр","en":"өчигдөр","hsk_level":1},
{"word":"做","pinyin":"zuò","definition":"хийх","en":"хийх","hsk_level":1},
{"word":"坐","pinyin":"zuò","definition":"суух","en":"суух","hsk_level":1},
{"word":"吧","pinyin":"ba","definition":"уу/үү (зөвлөх сул үг)","en":"уу/үү (зөвлөх сул үг)","hsk_level":2},
{"word":"白","pinyin":"bái","definition":"цагаан","en":"цагаан","hsk_level":2},
{"word":"百","pinyin":"bǎi","definition":"зуу","en":"зуу","hsk_level":2},
{"word":"帮助","pinyin":"bāngzhù","definition":"туслах","en":"туслах","hsk_level":2},
{"word":"报纸","pinyin":"bàozhǐ","definition":"сонин","en":"сонин","hsk_level":2},
{"word":"比","pinyin":"bǐ","definition":"-аас илүү, харьцуулах","en":"-аас илүү, харьцуулах","hsk_level":2},
{"word":"别","pinyin":"bié","definition":"битгий, өөр","en":"битгий, өөр","hsk_level":2},
{"word":"宾馆","pinyin":"bīnguǎn","definition":"зочид буудал","en":"зочид буудал","hsk_level":2},
{"word":"长","pinyin":"cháng","definition":"урт","en":"урт","hsk_level":2},
{"word":"唱歌","pinyin":"chànggē","definition":"дуулах","en":"дуулах","hsk_level":2},
{"word":"出","pinyin":"chū","definition":"гарах","en":"гарах","hsk_level":2},
{"word":"穿","pinyin":"chuān","definition":"өмсөх","en":"өмсөх","hsk_level":2},
{"word":"次","pinyin":"cì","definition":"удаа","en":"удаа","hsk_level":2},
{"word":"从","pinyin":"cóng","definition":"-аас, эхлэн","en":"-аас, эхлэн","hsk_level":2},
{"word":"错","pinyin":"cuò","definition":"буруу, алдаа","en":"буруу, алдаа","hsk_level":2},
{"word":"打篮球","pinyin":"dǎ lánqiú","definition":"сагсан бөмбөг тоглох","en":"сагсан бөмбөг тоглох","hsk_level":2},
{"word":"大家","pinyin":"dàjiā","definition":"бүгдээрээ, хүн бүр","en":"бүгдээрээ, хүн бүр","hsk_level":2},
{"word":"但是","pinyin":"dànshì","definition":"гэвч, гэхдээ","en":"гэвч, гэхдээ","hsk_level":2},
{"word":"等","pinyin":"děng","definition":"хүлээх","en":"хүлээх","hsk_level":2},
{"word":"弟弟","pinyin":"dìdi","definition":"дүү (эрэгтэй)","en":"дүү (эрэгтэй)","hsk_level":2},
{"word":"第一","pinyin":"dì yī","definition":"нэгдүгээр, анхны","en":"нэгдүгээр, анхны","hsk_level":2},
{"word":"懂","pinyin":"dǒng","definition":"ойлгох","en":"ойлгох","hsk_level":2},
{"word":"对","pinyin":"duì","definition":"зөв, тийм","en":"зөв, тийм","hsk_level":2},
{"word":"房间","pinyin":"fángjiān","definition":"өрөө","en":"өрөө","hsk_level":2},
{"word":"非常","pinyin":"fēicháng","definition":"маш их","en":"маш их","hsk_level":2},
{"word":"服务员","pinyin":"fúwùyuán","definition":"үйлчлэгч","en":"үйлчлэгч","hsk_level":2},
{"word":"告诉","pinyin":"gàosu","definition":"хэлэх, мэдэгдэх","en":"хэлэх, мэдэгдэх","hsk_level":2},
{"word":"哥哥","pinyin":"gēge","definition":"ах","en":"ах","hsk_level":2},
{"word":"给","pinyin":"gěi","definition":"өгөх","en":"өгөх","hsk_level":2},
{"word":"公共汽车","pinyin":"gōnggòng qìchē","definition":"автобус","en":"автобус","hsk_level":2},
{"word":"公司","pinyin":"gōngsī","definition":"компани","en":"компани","hsk_level":2},
{"word":"贵","pinyin":"guì","definition":"үнэтэй","en":"үнэтэй","hsk_level":2},
{"word":"过","pinyin":"guò","definition":"өнгөрөх, -ж үзэх","en":"өнгөрөх, -ж үзэх","hsk_level":2},
{"word":"还","pinyin":"hái","definition":"бас, хэвээрээ","en":"бас, хэвээрээ","hsk_level":2},
{"word":"孩子","pinyin":"háizi","definition":"хүүхэд","en":"хүүхэд","hsk_level":2},
{"word":"好吃","pinyin":"hǎochī","definition":"амттай","en":"амттай","hsk_level":2},
{"word":"黑","pinyin":"hēi","definition":"хар","en":"хар","hsk_level":2},
{"word":"红","pinyin":"hóng","definition":"улаан","en":"улаан","hsk_level":2},
{"word":"候机楼","pinyin":"hòujī lóu","definition":"нисэх буудлын зал","en":"нисэх буудлын зал","hsk_level":2},
{"word":"护照","pinyin":"hùzhào","definition":"гадаад паспорт","en":"гадаад паспорт","hsk_level":2},
{"word":"花","pinyin":"huā","definition":"цэцэг, зарцуулах","en":"цэцэг, зарцуулах","hsk_level":2},
{"word":"还是","pinyin":"háishi","definition":"эсвэл","en":"эсвэл","hsk_level":2},
{"word":"换","pinyin":"huàn","definition":"солих","en":"солих","hsk_level":2},
{"word":"黄","pinyin":"huáng","definition":"шар","en":"шар","hsk_level":2},
{"word":"回答","pinyin":"huídá","definition":"хариулах","en":"хариулах","hsk_level":2},
{"word":"机场","pinyin":"jīchǎng","definition":"нисэх буудал","en":"нисэх буудал","hsk_level":2},
{"word":"鸡蛋","pinyin":"jīdàn","definition":"тахианы өндөг","en":"тахианы өндөг","hsk_level":2},
{"word":"记得","pinyin":"jìde","definition":"санах","en":"санах","hsk_level":2},
{"word":"教室","pinyin":"jiàoshì","definition":"анги танхим","en":"анги танхим","hsk_level":2},
{"word":"姐姐","pinyin":"jiějie","definition":"эгч","en":"эгч","hsk_level":2},
{"word":"介绍","pinyin":"jièshào","definition":"танилцуулах","en":"танилцуулах","hsk_level":2},
{"word":"进","pinyin":"jìn","definition":"орох","en":"орох","hsk_level":2},
{"word":"近","pinyin":"jìn","definition":"ойрхон","en":"ойрхон","hsk_level":2},
{"word":"经常","pinyin":"jīngcháng","definition":"байнга, олонтаа","en":"байнга, олонтаа","hsk_level":2},
{"word":"旧","pinyin":"jiù","definition":"хуучин","en":"хуучин","hsk_level":2},
{"word":"就","pinyin":"jiù","definition":"тэгээд л, л","en":"тэгээд л, л","hsk_level":2},
{"word":"觉得","pinyin":"juéde","definition":"санагдах, бодох","en":"санагдах, бодох","hsk_level":2},
{"word":"开始","pinyin":"kāishǐ","definition":"эхлэх","en":"эхлэх","hsk_level":2},
{"word":"考试","pinyin":"kǎoshì","definition":"шалгалт","en":"шалгалт","hsk_level":2},
{"word":"可能","pinyin":"kěnéng","definition":"магадгүй, боломжтой","en":"магадгүй, боломжтой","hsk_level":2},
{"word":"可以","pinyin":"kěyǐ","definition":"болно, чадна","en":"болно, чадна","hsk_level":2},
{"word":"客气","pinyin":"kèqi","definition":"ёсорхох, найрсаг","en":"ёсорхох, найрсаг","hsk_level":2},
{"word":"空调","pinyin":"kōngtiáo","definition":"агааржуулагч","en":"агааржуулагч","hsk_level":2},
{"word":"哭","pinyin":"kū","definition":"уйлах","en":"уйлах","hsk_level":2},
{"word":"快","pinyin":"kuài","definition":"хурдан","en":"хурдан","hsk_level":2},
{"word":"来自","pinyin":"lái zì","definition":"-аас ирсэн","en":"-аас ирсэн","hsk_level":2},
{"word":"老","pinyin":"lǎo","definition":"хөгшин","en":"хөгшин","hsk_level":2},
{"word":"离","pinyin":"lí","definition":"-аас (зай)","en":"-аас (зай)","hsk_level":2},
{"word":"两","pinyin":"liǎng","definition":"хоёр","en":"хоёр","hsk_level":2},
{"word":"零","pinyin":"líng","definition":"тэг","en":"тэг","hsk_level":2},
{"word":"留学","pinyin":"liúxué","definition":"гадаадад суралцах","en":"гадаадад суралцах","hsk_level":2},
{"word":"路","pinyin":"lù","definition":"зам","en":"зам","hsk_level":2},
{"word":"旅游","pinyin":"lǚyóu","definition":"аялах","en":"аялах","hsk_level":2},
{"word":"妹妹","pinyin":"mèimei","definition":"дүү (эмэгтэй)","en":"дүү (эмэгтэй)","hsk_level":2},
{"word":"门","pinyin":"mén","definition":"хаалга","en":"хаалга","hsk_level":2},
{"word":"面包","pinyin":"miànbāo","definition":"талх","en":"талх","hsk_level":2},
{"word":"明白","pinyin":"míngbai","definition":"ойлгох","en":"ойлгох","hsk_level":2},
{"word":"拿","pinyin":"ná","definition":"авах, барих","en":"авах, барих","hsk_level":2},
{"word":"男","pinyin":"nán","definition":"эрэгтэй","en":"эрэгтэй","hsk_level":2},
{"word":"您","pinyin":"nín","definition":"Та","en":"Та","hsk_level":2},
{"word":"牛奶","pinyin":"niúnǎi","definition":"сүү","en":"сүү","hsk_level":2},
{"word":"旁边","pinyin":"pángbiān","definition":"хажуу","en":"хажуу","hsk_level":2},
{"word":"跑步","pinyin":"pǎobù","definition":"гүйх","en":"гүйх","hsk_level":2},
{"word":"便宜","pinyin":"piányi","definition":"хямдхан","en":"хямдхан","hsk_level":2},
{"word":"票","pinyin":"piào","definition":"тасалбар","en":"тасалбар","hsk_level":2},
{"word":"妻子","pinyin":"qīzi","definition":"эхнэр","en":"эхнэр","hsk_level":2},
{"word":"起床","pinyin":"qǐchuáng","definition":"ороосоо босох","en":"ороосоо босох","hsk_level":2},
{"word":"起来","pinyin":"qǐlái","definition":"босох","en":"босох","hsk_level":2},
{"word":"铅笔","pinyin":"qiānbǐ","definition":"харандаа","en":"харандаа","hsk_level":2},
{"word":"清楚","pinyin":"qīngchǔ","definition":"тодорхой","en":"тодорхой","hsk_level":2},
{"word":"请进","pinyin":"qǐng jìn","definition":"орно уу","en":"орно уу","hsk_level":2},
{"word":"去年","pinyin":"qùnián","definition":"өнгөрсөн жил","en":"өнгөрсөн жил","hsk_level":2},
{"word":"让","pinyin":"ràng","definition":"зөвшөөрөх, -уулах","en":"зөвшөөрөх, -уулах","hsk_level":2},
{"word":"认为","pinyin":"rènwéi","definition":"гэж үзэх, бодох","en":"гэж үзэх, бодох","hsk_level":2},
{"word":"日","pinyin":"rì","definition":"өдөр, нар","en":"өдөр, нар","hsk_level":2},
{"word":"如果","pinyin":"rúguǒ","definition":"хэрвээ","en":"хэрвээ","hsk_level":2},
{"word":"身体","pinyin":"shēntǐ","definition":"бие, эрүүл мэнд","en":"бие, эрүүл мэнд","hsk_level":2},
{"word":"生病","pinyin":"shēng bìng","definition":"өвдөх","en":"өвдөх","hsk_level":2},
{"word":"生活","pinyin":"shēnghuó","definition":"амьдрал, амьдрах","en":"амьдрал, амьдрах","hsk_level":2},
{"word":"生日","pinyin":"shēngrì","definition":"төрсөн өдөр","en":"төрсөн өдөр","hsk_level":2},
{"word":"时间","pinyin":"shíjiān","definition":"цаг хугацаа","en":"цаг хугацаа","hsk_level":2},
{"word":"瘦","pinyin":"shòu","definition":"туранхай","en":"туранхай","hsk_level":2},
{"word":"叔叔","pinyin":"shūshu","definition":"авга ах","en":"авга ах","hsk_level":2},
{"word":"送","pinyin":"sòng","definition":"бэлэглэх, хүргэх","en":"бэлэглэх, хүргэх","hsk_level":2},
{"word":"虽然","pinyin":"suīrán","definition":"хэдийгээр","en":"хэдийгээр","hsk_level":2},
{"word":"它","pinyin":"tā","definition":"тэр (амьтан, юмс)","en":"тэр (амьтан, юмс)","hsk_level":2},
{"word":"踢足球","pinyin":"tī zúqiú","definition":"хөлбөмбөг тоглох","en":"хөлбөмбөг тоглох","hsk_level":2},
{"word":"题","pinyin":"tí","definition":"даалгавар, асуулт","en":"даалгавар, асуулт","hsk_level":2},
{"word":"跳舞","pinyin":"tiàowǔ","definition":"бүжиглэх","en":"бүжиглэх","hsk_level":2},
{"word":"听说","pinyin":"tīngshuō","definition":"гэж сонссон","en":"гэж сонссон","hsk_level":2},
{"word":"外","pinyin":"wài","definition":"гадна","en":"гадна","hsk_level":2},
{"word":"完","pinyin":"wán","definition":"дуусах","en":"дуусах","hsk_level":2},
{"word":"玩","pinyin":"wán","definition":"тоглох, зугаацах","en":"тоглох, зугаацах","hsk_level":2},
{"word":"晚上","pinyin":"wǎnshang","definition":"орой","en":"орой","hsk_level":2},
{"word":"往","pinyin":"wǎng","definition":"чиглэн","en":"чиглэн","hsk_level":2},
{"word":"为什么","pinyin":"wèishénme","definition":"яагаад","en":"яагаад","hsk_level":2},
{"word":"问","pinyin":"wèn","definition":"асуух","en":"асуух","hsk_level":2},
{"word":"问题","pinyin":"wèntí","definition":"асуулт, асуудал","en":"асуулт, асуудал","hsk_level":2},
{"word":"西瓜","pinyin":"xīguā","definition":"тарвас","en":"тарвас","hsk_level":2},
{"word":"希望","pinyin":"xīwàng","definition":"найдах, хүсэх","en":"найдах, хүсэх","hsk_level":2},
{"word":"小时","pinyin":"xiǎoshí","definition":"цаг (хугацаа)","en":"цаг (хугацаа)","hsk_level":2},
{"word":"笑","pinyin":"xiào","definition":"инээх","en":"инээх","hsk_level":2},
{"word":"新","pinyin":"xīn","definition":"шинэ","en":"шинэ","hsk_level":2},
{"word":"信","pinyin":"xìn","definition":"захидал, итгэх","en":"захидал, итгэх","hsk_level":2},
{"word":"行","pinyin":"xíng","definition":"болно","en":"болно","hsk_level":2},
{"word":"休息","pinyin":"xiūxi","definition":"амрах","en":"амрах","hsk_level":2},
{"word":"需要","pinyin":"xūyào","definition":"хэрэгтэй","en":"хэрэгтэй","hsk_level":2},
{"word":"选择","pinyin":"xuǎnzé","definition":"сонгох","en":"сонгох","hsk_level":2},
{"word":"颜色","pinyin":"yánsè","definition":"өнгө","en":"өнгө","hsk_level":2},
{"word":"眼睛","pinyin":"yǎnjing","definition":"нүд","en":"нүд","hsk_level":2},
{"word":"药","pinyin":"yào","definition":"эм","en":"эм","hsk_level":2},
{"word":"也","pinyin":"yě","definition":"бас, мөн","en":"бас, мөн","hsk_level":2},
{"word":"以为","pinyin":"yǐwéi","definition":"гэж бодох (буруугаар)","en":"гэж бодох (буруугаар)","hsk_level":2},
{"word":"意思","pinyin":"yìsi","definition":"утга, санаа","en":"утга, санаа","hsk_level":2},
{"word":"因为","pinyin":"yīnwèi","definition":"учраас","en":"учраас","hsk_level":2},
{"word":"音乐","pinyin":"yīnyuè","definition":"хөгжим","en":"хөгжим","hsk_level":2},
{"word":"影响","pinyin":"yǐngxiǎng","definition":"нөлөөлөх","en":"нөлөөлөх","hsk_level":2},
{"word":"用","pinyin":"yòng","definition":"хэрэглэх","en":"хэрэглэх","hsk_level":2},
{"word":"游泳","pinyin":"yóuyǒng","definition":"усанд сэлэх","en":"усанд сэлэх","hsk_level":2},
{"word":"又","pinyin":"yòu","definition":"дахин, бас","en":"дахин, бас","hsk_level":2},
{"word":"右边","pinyin":"yòubian","definition":"баруун тал","en":"баруун тал","hsk_level":2},
{"word":"遇到","pinyin":"yùdào","definition":"таарах","en":"таарах","hsk_level":2},
{"word":"元","pinyin":"yuán","definition":"юань","en":"юань","hsk_level":2},
{"word":"远","pinyin":"yuǎn","definition":"хол","en":"хол","hsk_level":2},
{"word":"运动","pinyin":"yùndòng","definition":"спорт, дасгал хийх","en":"спорт, дасгал хийх","hsk_level":2},
{"word":"再","pinyin":"zài","definition":"дахин","en":"дахин","hsk_level":2},
{"word":"早上","pinyin":"zǎoshang","definition":"өглөө","en":"өглөө","hsk_level":2},
{"word":"丈夫","pinyin":"zhàngfu","definition":"нөхөр","en":"нөхөр","hsk_level":2},
{"word":"找","pinyin":"zhǎo","definition":"хайх, олох","en":"хайх, олох","hsk_level":2},
{"word":"这里","pinyin":"zhèlǐ","definition":"энд","en":"энд","hsk_level":2},
{"word":"这些","pinyin":"zhèxiē","definition":"эдгээр","en":"эдгээр","hsk_level":2},
{"word":"中间","pinyin":"zhōngjiān","definition":"дунд","en":"дунд","hsk_level":2},
{"word":"重要","pinyin":"zhòngyào","definition":"чухал","en":"чухал","hsk_level":2},
{"word":"主要","pinyin":"zhǔyào","definition":"гол, голлох","en":"гол, голлох","hsk_level":2},
{"word":"准备","pinyin":"zhǔnbèi","definition":"бэлдэх","en":"бэлдэх","hsk_level":2},
{"word":"字典","pinyin":"zìdiǎn","definition":"толь бичиг","en":"толь бичиг","hsk_level":2},
{"word":"走","pinyin":"zǒu","definition":"алхах, явах","en":"алхах, явах","hsk_level":2},
{"word":"最","pinyin":"zuì","definition":"хамгийн","en":"хамгийн","hsk_level":2},
{"word":"最近","pinyin":"zuìjìn","definition":"ойрд, саяхан","en":"ойрд, саяхан","hsk_level":2},
{"word":"左边","pinyin":"zuǒbian","definition":"зүүн тал","en":"зүүн тал","hsk_level":2},
{"word":"阿姨","pinyin":"āyí","definition":"нагац эгч","en":"нагац эгч","hsk_level":3},
{"word":"啊","pinyin":"a","definition":"аа (гайхах сул үг)","en":"аа (гайхах сул үг)","hsk_level":3},
{"word":"矮","pinyin":"ǎi","definition":"намхан","en":"намхан","hsk_level":3},
{"word":"爱好","pinyin":"àihào","definition":"сонирхол, хобби","en":"сонирхол, хобби","hsk_level":3},
{"word":"安静","pinyin":"ānjìng","definition":"чимээгүй, тайван","en":"чимээгүй, тайван","hsk_level":3},
{"word":"把","pinyin":"bǎ","definition":"-ыг/-ийг (үйлдэл заах нөхцөл)","en":"-ыг/-ийг (үйлдэл заах нөхцөл)","hsk_level":3},
{"word":"班","pinyin":"bān","definition":"анги, ээлж","en":"анги, ээлж","hsk_level":3},
{"word":"搬","pinyin":"bān","definition":"нүүх, зөөх","en":"нүүх, зөөх","hsk_level":3},
{"word":"半","pinyin":"bàn","definition":"хагас","en":"хагас","hsk_level":3},
{"word":"帮","pinyin":"bāng","definition":"туслах","en":"туслах","hsk_level":3},
{"word":"包","pinyin":"bāo","definition":"цүнх, боох","en":"цүнх, боох","hsk_level":3},
{"word":"饱","pinyin":"bǎo","definition":"цадах","en":"цадах","hsk_level":3},
{"word":"北方","pinyin":"běifāng","definition":"хойд зүг","en":"хойд зүг","hsk_level":3},
{"word":"被","pinyin":"bèi","definition":"-д/-т (идэвхгүй хэв)","en":"-д/-т (идэвхгүй хэв)","hsk_level":3},
{"word":"鼻子","pinyin":"bízi","definition":"хамар","en":"хамар","hsk_level":3},
{"word":"比较","pinyin":"bǐjiào","definition":"харьцангуй","en":"харьцангуй","hsk_level":3},
{"word":"比赛","pinyin":"bǐsài","definition":"тэмцээн","en":"тэмцээн","hsk_level":3},
{"word":"必须","pinyin":"bìxū","definition":"заавал, ёстой","en":"заавал, ёстой","hsk_level":3},
{"word":"变化","pinyin":"biànhuà","definition":"өөрчлөлт","en":"өөрчлөлт","hsk_level":3},
{"word":"表示","pinyin":"biǎoshì","definition":"илэрхийлэх","en":"илэрхийлэх","hsk_level":3},
{"word":"表演","pinyin":"biǎoyǎn","definition":"тоглолт, үзүүлбэр","en":"тоглолт, үзүүлбэр","hsk_level":3},
{"word":"别人","pinyin":"biérén","definition":"бусад хүн","en":"бусад хүн","hsk_level":3},
{"word":"冰箱","pinyin":"bīngxiāng","definition":"хөргөгч","en":"хөргөгч","hsk_level":3},
{"word":"不但","pinyin":"bùdàn","definition":"зөвхөн барахгүй","en":"зөвхөн барахгүй","hsk_level":3},
{"word":"不过","pinyin":"búguò","definition":"гэхдээ л","en":"гэхдээ л","hsk_level":3},
{"word":"参加","pinyin":"cānjiā","definition":"оролцох","en":"оролцох","hsk_level":3},
{"word":"草","pinyin":"cǎo","definition":"өвс","en":"өвс","hsk_level":3},
{"word":"层","pinyin":"céng","definition":"давхар","en":"давхар","hsk_level":3},
{"word":"差","pinyin":"chà","definition":"дутуу, муу","en":"дутуу, муу","hsk_level":3},
{"word":"菜单","pinyin":"càidān","definition":"хоолны цэс","en":"хоолны цэс","hsk_level":3},
{"word":"超市","pinyin":"chāoshì","definition":"супермаркет","en":"супермаркет","hsk_level":3},
{"word":"成绩","pinyin":"chéngjì","definition":"дүн, амжилт","en":"дүн, амжилт","hsk_level":3},
{"word":"城市","pinyin":"chéngshì","definition":"хот","en":"хот","hsk_level":3},
{"word":"迟到","pinyin":"chídào","definition":"хоцрох","en":"хоцрох","hsk_level":3},
{"word":"出现","pinyin":"chūxiàn","definition":"гарч ирэх","en":"гарч ирэх","hsk_level":3},
{"word":"厨房","pinyin":"chúfáng","definition":"гал тогоо","en":"гал тогоо","hsk_level":3},
{"word":"除了","pinyin":"chúle","definition":"-аас гадна","en":"-аас гадна","hsk_level":3},
{"word":"春","pinyin":"chūn","definition":"хавар","en":"хавар","hsk_level":3},
{"word":"聪明","pinyin":"cōngming","definition":"ухаалаг","en":"ухаалаг","hsk_level":3},
{"word":"打扫","pinyin":"dǎsǎo","definition":"цэвэрлэх","en":"цэвэрлэх","hsk_level":3},
{"word":"打算","pinyin":"dǎsuàn","definition":"төлөвлөх","en":"төлөвлөх","hsk_level":3},
{"word":"大概","pinyin":"dàgài","definition":"бараг, магадгүй","en":"бараг, магадгүй","hsk_level":3},
{"word":"大声","pinyin":"dàshēng","definition":"чанга дуугаар","en":"чанга дуугаар","hsk_level":3},
{"word":"带","pinyin":"dài","definition":"авч явах, дагуулах","en":"авч явах, дагуулах","hsk_level":3},
{"word":"担心","pinyin":"dānxīn","definition":"санаа зовох","en":"санаа зовох","hsk_level":3},
{"word":"蛋糕","pinyin":"dàngāo","definition":"бялуу","en":"бялуу","hsk_level":3},
{"word":"当然","pinyin":"dāngrán","definition":"мэдээж","en":"мэдээж","hsk_level":3},
{"word":"地","pinyin":"de","definition":"-аар/-ээр (тодотгол нөхцөл)","en":"-аар/-ээр (тодотгол нөхцөл)","hsk_level":3},
{"word":"地方","pinyin":"dìfang","definition":"газар, нутаг","en":"газар, нутаг","hsk_level":3},
{"word":"地图","pinyin":"dìtú","definition":"газрын зураг","en":"газрын зураг","hsk_level":3},
{"word":"电梯","pinyin":"diàntī","definition":"цахилгаан шат","en":"цахилгаан шат","hsk_level":3},
{"word":"电子邮件","pinyin":"diànzǐ yóujiàn","definition":"имэйл","en":"имэйл","hsk_level":3},
{"word":"东","pinyin":"dōng","definition":"зүүн зүг","en":"зүүн зүг","hsk_level":3},
{"word":"动物","pinyin":"dòngwù","definition":"амьтан","en":"амьтан","hsk_level":3},
{"word":"短","pinyin":"duǎn","definition":"богино","en":"богино","hsk_level":3},
{"word":"段","pinyin":"duàn","definition":"хэсэг, үе","en":"хэсэг, үе","hsk_level":3},
{"word":"锻炼","pinyin":"duànliàn","definition":"дасгал хийх","en":"дасгал хийх","hsk_level":3},
{"word":"多久","pinyin":"duō jiǔ","definition":"хэр удаан","en":"хэр удаан","hsk_level":3},
{"word":"多么","pinyin":"duōme","definition":"ямар их","en":"ямар их","hsk_level":3},
{"word":"饿","pinyin":"è","definition":"өлсөх","en":"өлсөх","hsk_level":3},
{"word":"而且","pinyin":"érqiě","definition":"бөгөөд, түүнчлэн","en":"бөгөөд, түүнчлэн","hsk_level":3},
{"word":"耳朵","pinyin":"ěrduo","definition":"чих","en":"чих","hsk_level":3},
{"word":"方便","pinyin":"fāngbiàn","definition":"тухтай, амар","en":"тухтай, амар","hsk_level":3},
{"word":"放","pinyin":"fàng","definition":"тавих, суллах","en":"тавих, суллах","hsk_level":3},
{"word":"放心","pinyin":"fàngxīn","definition":"санаа амрах","en":"санаа амрах","hsk_level":3},
{"word":"分","pinyin":"fēn","definition":"минут, оноо, хуваах","en":"минут, оноо, хуваах","hsk_level":3},
{"word":"复习","pinyin":"fùxí","definition":"давтах","en":"давтах","hsk_level":3},
{"word":"感觉","pinyin":"gǎnjué","definition":"мэдрэх, мэдрэмж","en":"мэдрэх, мэдрэмж","hsk_level":3},
{"word":"感情","pinyin":"gǎnqíng","definition":"сэтгэл хөдлөл","en":"сэтгэл хөдлөл","hsk_level":3},
{"word":"干净","pinyin":"gānjìng","definition":"цэвэрхэн","en":"цэвэрхэн","hsk_level":3},
{"word":"刚才","pinyin":"gāngcái","definition":"саяхан","en":"саяхан","hsk_level":3},
{"word":"高","pinyin":"gāo","definition":"өндөр","en":"өндөр","hsk_level":3},
{"word":"各","pinyin":"gè","definition":"бүр, тус бүр","en":"бүр, тус бүр","hsk_level":3},
{"word":"跟","pinyin":"gēn","definition":"-той/-тэй, дагах","en":"-той/-тэй, дагах","hsk_level":3},
{"word":"根据","pinyin":"gēnjù","definition":"үндэслэн","en":"үндэслэн","hsk_level":3},
{"word":"更","pinyin":"gèng","definition":"бүр, улам","en":"бүр, улам","hsk_level":3},
{"word":"公里","pinyin":"gōnglǐ","definition":"километр","en":"километр","hsk_level":3},
{"word":"公园","pinyin":"gōngyuán","definition":"цэцэрлэгт хүрээлэн","en":"цэцэрлэгт хүрээлэн","hsk_level":3},
{"word":"故事","pinyin":"gùshi","definition":"түүх, өгүүлэг","en":"түүх, өгүүлэг","hsk_level":3},
{"word":"关系","pinyin":"guānxi","definition":"харилцаа","en":"харилцаа","hsk_level":3},
{"word":"关心","pinyin":"guānxīn","definition":"санаа тавих","en":"санаа тавих","hsk_level":3},
{"word":"关于","pinyin":"guānyú","definition":"тухай","en":"тухай","hsk_level":3},
{"word":"国家","pinyin":"guójiā","definition":"улс орон","en":"улс орон","hsk_level":3},
{"word":"过去","pinyin":"guòqù","definition":"өнгөрсөн","en":"өнгөрсөн","hsk_level":3},
{"word":"还是","pinyin":"háishi","definition":"эсвэл, нь дээр","en":"эсвэл, нь дээр","hsk_level":3},
{"word":"寒假","pinyin":"hánjià","definition":"өвлийн амралт","en":"өвлийн амралт","hsk_level":3},
{"word":"好像","pinyin":"hǎoxiàng","definition":"бололтой, шиг","en":"бололтой, шиг","hsk_level":3},
{"word":"护士","pinyin":"hùshi","definition":"сувилагч","en":"сувилагч","hsk_level":3},
{"word":"互联网","pinyin":"hùliánwǎng","definition":"интернет","en":"интернет","hsk_level":3},
{"word":"花园","pinyin":"huāyuán","definition":"цэцэрлэг","en":"цэцэрлэг","hsk_level":3},
{"word":"环境","pinyin":"huánjìng","definition":"орчин","en":"орчин","hsk_level":3},
{"word":"还","pinyin":"huán","definition":"буцааж өгөх","en":"буцааж өгөх","hsk_level":3},
{"word":"机会","pinyin":"jīhuì","definition":"боломж","en":"боломж","hsk_level":3},
{"word":"季节","pinyin":"jìjié","definition":"улирал","en":"улирал","hsk_level":3},
{"word":"记","pinyin":"jì","definition":"цээжлэх, тэмдэглэх","en":"цээжлэх, тэмдэглэх","hsk_level":3},
{"word":"急","pinyin":"jí","definition":"яаруу, сандрах","en":"яаруу, сандрах","hsk_level":3},
{"word":"检查","pinyin":"jiǎnchá","definition":"шалгах","en":"шалгах","hsk_level":3},
{"word":"简单","pinyin":"jiǎndān","definition":"энгийн, амархан","en":"энгийн, амархан","hsk_level":3},
{"word":"健康","pinyin":"jiànkāng","definition":"эрүүл, эрүүл мэнд","en":"эрүүл, эрүүл мэнд","hsk_level":3},
{"word":"见面","pinyin":"jiànmiàn","definition":"уулзах","en":"уулзах","hsk_level":3},
{"word":"讲","pinyin":"jiǎng","definition":"ярих, тайлбарлах","en":"ярих, тайлбарлах","hsk_level":3},
{"word":"角","pinyin":"jiǎo","definition":"мао (мөнгөний нэгж), өнцөг","en":"мао (мөнгөний нэгж), өнцөг","hsk_level":3},
{"word":"结婚","pinyin":"jiéhūn","definition":"гэрлэх","en":"гэрлэх","hsk_level":3},
{"word":"解决","pinyin":"jiějué","definition":"шийдвэрлэх","en":"шийдвэрлэх","hsk_level":3},
{"word":"借","pinyin":"jiè","definition":"зээлэх","en":"зээлэх","hsk_level":3},
{"word":"经过","pinyin":"jīngguò","definition":"дамжин өнгөрөх","en":"дамжин өнгөрөх","hsk_level":3},
{"word":"经验","pinyin":"jīngyàn","definition":"туршлага","en":"туршлага","hsk_level":3},
{"word":"久","pinyin":"jiǔ","definition":"удаан","en":"удаан","hsk_level":3},
{"word":"就是","pinyin":"jiùshì","definition":"өөрөөр хэлбэл, тэр л","en":"өөрөөр хэлбэл, тэр л","hsk_level":3},
{"word":"举行","pinyin":"jǔxíng","definition":"зохион байгуулах","en":"зохион байгуулах","hsk_level":3},
{"word":"句子","pinyin":"jùzi","definition":"өгүүлбэр","en":"өгүүлбэр","hsk_level":3},
{"word":"决定","pinyin":"juédìng","definition":"шийдэх, шийдвэр","en":"шийдэх, шийдвэр","hsk_level":3},
{"word":"可爱","pinyin":"kě'ài","definition":"өхөөрдөм, хөөрхөн","en":"өхөөрдөм, хөөрхөн","hsk_level":3},
{"word":"可是","pinyin":"kěshì","definition":"гэвч, харин","en":"гэвч, харин","hsk_level":3},
{"word":"刻","pinyin":"kè","definition":"15 минут","en":"15 минут","hsk_level":3},
{"word":"客人","pinyin":"kèrén","definition":"зочин","en":"зочин","hsk_level":3},
{"word":"筷子","pinyin":"kuàizi","definition":"савх","en":"савх","hsk_level":3},
{"word":"来不及","pinyin":"lái bùjí","definition":"амжихгүй байх","en":"амжихгүй байх","hsk_level":3},
{"word":"冷静","pinyin":"lěngjìng","definition":"тайван, хянамгай","en":"тайван, хянамгай","hsk_level":3},
{"word":"历史","pinyin":"lìshǐ","definition":"түүх","en":"түүх","hsk_level":3},
{"word":"脸","pinyin":"liǎn","definition":"нүүр","en":"нүүр","hsk_level":3},
{"word":"练习","pinyin":"liànxí","definition":"дасгал, дадлага","en":"дасгал, дадлага","hsk_level":3},
{"word":"联系","pinyin":"liánxi","definition":"холбоо барих","en":"холбоо барих","hsk_level":3},
{"word":"了解","pinyin":"liǎojiě","definition":"ойлгож мэдэх","en":"ойлгож мэдэх","hsk_level":3},
{"word":"楼","pinyin":"lóu","definition":"байшин, давхар","en":"байшин, давхар","hsk_level":3},
{"word":"麻烦","pinyin":"máfan","definition":"төвөгтэй","en":"төвөгтэй","hsk_level":3},
{"word":"满意","pinyin":"mǎnyì","definition":"сэтгэл хангалуун","en":"сэтгэл хангалуун","hsk_level":3},
{"word":"帽子","pinyin":"màozi","definition":"малгай","en":"малгай","hsk_level":3},
{"word":"马上","pinyin":"mǎshàng","definition":"шууд, одоохон","en":"шууд, одоохон","hsk_level":3},
{"word":"每","pinyin":"měi","definition":"бүр, тутам","en":"бүр, тутам","hsk_level":3},
{"word":"迷","pinyin":"mí","definition":"шүтэгч, дурлагч","en":"шүтэгч, дурлагч","hsk_level":3},
{"word":"米","pinyin":"mǐ","definition":"метр, будаа","en":"метр, будаа","hsk_level":3},
{"word":"秘书","pinyin":"mìshū","definition":"нарийн бичгийн дарга","en":"нарийн бичгийн дарга","hsk_level":3},
{"word":"面","pinyin":"miàn","definition":"нүүр, тал, гоймон","en":"нүүр, тал, гоймон","hsk_level":3},
{"word":"明显","pinyin":"míngxiǎn","definition":"тодорхой, илэрхий","en":"тодорхой, илэрхий","hsk_level":3},
{"word":"奶奶","pinyin":"nǎinai","definition":"эмээ (аавын тал)","en":"эмээ (аавын тал)","hsk_level":3},
{"word":"难","pinyin":"nán","definition":"хэцүү","en":"хэцүү","hsk_level":3},
{"word":"难道","pinyin":"nándào","definition":"арай ... юм биш биз","en":"арай ... юм биш биз","hsk_level":3},
{"word":"南方","pinyin":"nánfāng","definition":"өмнөд зүг","en":"өмнөд зүг","hsk_level":3},
{"word":"年级","pinyin":"niánjí","definition":"анги, курс","en":"анги, курс","hsk_level":3},
{"word":"年轻","pinyin":"niánqīng","definition":"залуу","en":"залуу","hsk_level":3},
{"word":"努力","pinyin":"nǔlì","definition":"чармайх, хичээнгүй","en":"чармайх, хичээнгүй","hsk_level":3},
{"word":"暖和","pinyin":"nuǎnhuo","definition":"дулаахан","en":"дулаахан","hsk_level":3},
{"word":"爬山","pinyin":"pá shān","definition":"ууланд авирах","en":"ууланд авирах","hsk_level":3},
{"word":"怕","pinyin":"pà","definition":"айх","en":"айх","hsk_level":3},
{"word":"盘子","pinyin":"pánzi","definition":"таваг","en":"таваг","hsk_level":3},
{"word":"胖","pinyin":"pàng","definition":"тарган","en":"тарган","hsk_level":3},
{"word":"皮肤","pinyin":"pífū","definition":"арьс","en":"арьс","hsk_level":3},
{"word":"普通话","pinyin":"pǔtōnghuà","definition":"Путунхуа (албан ёсны хятад хэл)","en":"Путунхуа (албан ёсны хятад хэл)","hsk_level":3},
{"word":"其他","pinyin":"qítā","definition":"бусад","en":"бусад","hsk_level":3},
{"word":"奇怪","pinyin":"qíguài","definition":"хачин, сонин","en":"хачин, сонин","hsk_level":3},
{"word":"气候","pinyin":"qìhòu","definition":"цаг уур","en":"цаг уур","hsk_level":3},
{"word":"其实","pinyin":"qíshí","definition":"үнэндээ","en":"үнэндээ","hsk_level":3},
{"word":"千","pinyin":"qiān","definition":"мянга","en":"мянга","hsk_level":3},
{"word":"签证","pinyin":"qiānzhèng","definition":"виз","en":"виз","hsk_level":3},
{"word":"墙","pinyin":"qiáng","definition":"хана","en":"хана","hsk_level":3},
{"word":"桥","pinyin":"qiáo","definition":"гүүр","en":"гүүр","hsk_level":3},
{"word":"亲戚","pinyin":"qīnqi","definition":"хамаатан садан","en":"хамаатан садан","hsk_level":3},
{"word":"请假","pinyin":"qǐngjià","definition":"чөлөө гуйх","en":"чөлөө гуйх","hsk_level":3},
{"word":"裙子","pinyin":"qúnzi","definition":"даашинз","en":"даашинз","hsk_level":3},
{"word":"然后","pinyin":"ránhòu","definition":"тэгээд, дараа нь","en":"тэгээд, дараа нь","hsk_level":3},
{"word":"热情","pinyin":"rèqíng","definition":"найрсаг, дулаан","en":"найрсаг, дулаан","hsk_level":3},
{"word":"认真","pinyin":"rènzhēn","definition":"нухацтай","en":"нухацтай","hsk_level":3},
{"word":"容易","pinyin":"róngyì","definition":"амархан","en":"амархан","hsk_level":3},
{"word":"入口","pinyin":"rùkǒu","definition":"орох хаалга","en":"орох хаалга","hsk_level":3},
{"word":"伤心","pinyin":"shāngxīn","definition":"гуниглах","en":"гуниглах","hsk_level":3},
{"word":"上班","pinyin":"shàngbān","definition":"ажилдаа явах","en":"ажилдаа явах","hsk_level":3},
{"word":"声音","pinyin":"shēngyīn","definition":"дуу, чимээ","en":"дуу, чимээ","hsk_level":3},
{"word":"生气","pinyin":"shēngqì","definition":"уурлах","en":"уурлах","hsk_level":3},
{"word":"世界","pinyin":"shìjiè","definition":"дэлхий","en":"дэлхий","hsk_level":3},
{"word":"数学","pinyin":"shùxué","definition":"математик","en":"математик","hsk_level":3},
{"word":"数字","pinyin":"shùzì","definition":"тоо, цифр","en":"тоо, цифр","hsk_level":3},
{"word":"树","pinyin":"shù","definition":"мод","en":"мод","hsk_level":3},
{"word":"帅","pinyin":"shuài","definition":"царайлаг","en":"царайлаг","hsk_level":3},
{"word":"水平","pinyin":"shuǐpíng","definition":"түвшин","en":"түвшин","hsk_level":3},
{"word":"说话","pinyin":"shuōhuà","definition":"ярих","en":"ярих","hsk_level":3},
{"word":"死","pinyin":"sǐ","definition":"үхэх","en":"үхэх","hsk_level":3},
{"word":"速度","pinyin":"sùdù","definition":"хурд","en":"хурд","hsk_level":3},
{"word":"所有","pinyin":"suǒyǒu","definition":"бүх","en":"бүх","hsk_level":3},
{"word":"太阳","pinyin":"tàiyáng","definition":"нар","en":"нар","hsk_level":3},
{"word":"特别","pinyin":"tèbié","definition":"онцгой, ялангуяа","en":"онцгой, ялангуяа","hsk_level":3},
{"word":"体育","pinyin":"tǐyù","definition":"биеийн тамир","en":"биеийн тамир","hsk_level":3},
{"word":"提高","pinyin":"tígāo","definition":"дээшлүүлэх","en":"дээшлүүлэх","hsk_level":3},
{"word":"甜","pinyin":"tián","definition":"чихэрлэг","en":"чихэрлэг","hsk_level":3},
{"word":"条","pinyin":"tiáo","definition":"ширхэг (урт нарийн зүйл)","en":"ширхэг (урт нарийн зүйл)","hsk_level":3},
{"word":"通知","pinyin":"tōngzhī","definition":"мэдэгдэх, мэдэгдэл","en":"мэдэгдэх, мэдэгдэл","hsk_level":3},
{"word":"推","pinyin":"tuī","definition":"түлхэх","en":"түлхэх","hsk_level":3},
{"word":"腿","pinyin":"tuǐ","definition":"хөл","en":"хөл","hsk_level":3},
{"word":"完成","pinyin":"wánchéng","definition":"дуусгах, биелүүлэх","en":"дуусгах, биелүүлэх","hsk_level":3},
{"word":"忘","pinyin":"wàng","definition":"мартах","en":"мартах","hsk_level":3},
{"word":"网球","pinyin":"wǎngqiú","definition":"теннис","en":"теннис","hsk_level":3},
{"word":"卫生间","pinyin":"wèishēngjiān","definition":"угаалгын өрөө","en":"угаалгын өрөө","hsk_level":3},
{"word":"为了","pinyin":"wèile","definition":"-ын тулд","en":"-ын тулд","hsk_level":3},
{"word":"位","pinyin":"wèi","definition":"хүн (хүндэтгэлийн тоолох үг)","en":"хүн (хүндэтгэлийн тоолох үг)","hsk_level":3},
{"word":"文化","pinyin":"wénhuà","definition":"соёл","en":"соёл","hsk_level":3},
{"word":"习惯","pinyin":"xíguàn","definition":"зуршил, дасах","en":"зуршил, дасах","hsk_level":3},
{"word":"洗手间","pinyin":"xǐshǒujiān","definition":"бие засах газар","en":"бие засах газар","hsk_level":3},
{"word":"先","pinyin":"xiān","definition":"түрүүлж, эхлээд","en":"түрүүлж, эхлээд","hsk_level":3},
{"word":"向","pinyin":"xiàng","definition":"чиглэлд","en":"чиглэлд","hsk_level":3},
{"word":"像","pinyin":"xiàng","definition":"адилхан байх","en":"адилхан байх","hsk_level":3},
{"word":"小吃","pinyin":"xiǎochī","definition":"хөнгөн зууш","en":"хөнгөн зууш","hsk_level":3},
{"word":"笑话","pinyin":"xiàohuà","definition":"онигоо","en":"онигоо","hsk_level":3},
{"word":"心情","pinyin":"xīnqíng","definition":"сэтгэл санаа","en":"сэтгэл санаа","hsk_level":3},
{"word":"信息","pinyin":"xìnxi","definition":"мэдээлэл","en":"мэдээлэл","hsk_level":3},
{"word":"行李箱","pinyin":"xíngli xiāng","definition":"чемодан","en":"чемодан","hsk_level":3},
{"word":"要求","pinyin":"yāoqiú","definition":"шаардах, шаардлага","en":"шаардах, шаардлага","hsk_level":3},
{"word":"也许","pinyin":"yěxǔ","definition":"магадгүй","en":"магадгүй","hsk_level":3},
{"word":"一般","pinyin":"yībān","definition":"ердийн","en":"ердийн","hsk_level":3},
{"word":"一定","pinyin":"yīdìng","definition":"заавал, гарцаагүй","en":"заавал, гарцаагүй","hsk_level":3},
{"word":"一共","pinyin":"yīgòng","definition":"нийт","en":"нийт","hsk_level":3},
{"word":"一会儿","pinyin":"yīhuìr","definition":"хэсэг хугацааны дараа","en":"хэсэг хугацааны дараа","hsk_level":3},
{"word":"一样","pinyin":"yīyàng","definition":"адилхан","en":"адилхан","hsk_level":3},
{"word":"已经","pinyin":"yǐjīng","definition":"аль хэдийн","en":"аль хэдийн","hsk_level":3},
{"word":"以前","pinyin":"yǐqián","definition":"өмнө, урьд нь","en":"өмнө, урьд нь","hsk_level":3},
{"word":"一直","pinyin":"yīzhí","definition":"чигээрээ, дандаа","en":"чигээрээ, дандаа","hsk_level":3},
{"word":"以后","pinyin":"yǐhòu","definition":"дараа, хойшид","en":"дараа, хойшид","hsk_level":3},
{"word":"因此","pinyin":"yīncǐ","definition":"иймээс, үүний улмаас","en":"иймээс, үүний улмаас","hsk_level":3},
{"word":"银行","pinyin":"yínháng","definition":"банк","en":"банк","hsk_level":3},
{"word":"应该","pinyin":"yīnggāi","definition":"ёстой","en":"ёстой","hsk_level":3},
{"word":"由于","pinyin":"yóuyú","definition":"-аас болоод","en":"-аас болоод","hsk_level":3},
{"word":"原来","pinyin":"yuánlái","definition":"уул нь, байз даа","en":"уул нь, байз даа","hsk_level":3},
{"word":"允许","pinyin":"yǔnxǔ","definition":"зөвшөөрөх","en":"зөвшөөрөх","hsk_level":3},
{"word":"增加","pinyin":"zēngjiā","definition":"нэмэгдүүлэх","en":"нэмэгдүүлэх","hsk_level":3},
{"word":"站","pinyin":"zhàn","definition":"зогсох, буудал","en":"зогсох, буудал","hsk_level":3},
{"word":"长大","pinyin":"zhǎngdà","definition":"өсөж томрох","en":"өсөж томрох","hsk_level":3},
{"word":"着急","pinyin":"zháojí","definition":"сандрах, яарах","en":"сандрах, яарах","hsk_level":3},
{"word":"真","pinyin":"zhēn","definition":"үнэхээр","en":"үнэхээр","hsk_level":3},
{"word":"整理","pinyin":"zhěnglǐ","definition":"цэгцлэх","en":"цэгцлэх","hsk_level":3},
{"word":"正在","pinyin":"zhèngzài","definition":"яг одоо хийж байх","en":"яг одоо хийж байх","hsk_level":3},
{"word":"只","pinyin":"zhǐ","definition":"зөвхөн","en":"зөвхөн","hsk_level":3},
{"word":"只有","pinyin":"zhǐyǒu","definition":"зөвхөн ... байж л","en":"зөвхөн ... байж л","hsk_level":3},
{"word":"终于","pinyin":"zhōngyú","definition":"эцэст нь","en":"эцэст нь","hsk_level":3},
{"word":"中文","pinyin":"zhōngwén","definition":"Хятад хэл (бичгийн)","en":"Хятад хэл (бичгийн)","hsk_level":3},
{"word":"重","pinyin":"zhòng","definition":"хүнд","en":"хүнд","hsk_level":3},
{"word":"种","pinyin":"zhǒng","definition":"төрөл, зүйл","en":"төрөл, зүйл","hsk_level":3},
{"word":"周末","pinyin":"zhōumò","definition":"амралтын өдрүүд","en":"амралтын өдрүүд","hsk_level":3},
{"word":"祝","pinyin":"zhù","definition":"ерөөх","en":"ерөөх","hsk_level":3},
{"word":"注意","pinyin":"zhùyì","definition":"анхаарах","en":"анхаарах","hsk_level":3},
{"word":"专业","pinyin":"zhuānyè","definition":"мэргэжил","en":"мэргэжил","hsk_level":3},
{"word":"自己","pinyin":"zìjǐ","definition":"өөрөө","en":"өөрөө","hsk_level":3},
{"word":"总是","pinyin":"zǒngshì","definition":"дандаа, үргэлж","en":"дандаа, үргэлж","hsk_level":3},
{"word":"最后","pinyin":"zuìhòu","definition":"эцэст нь","en":"эцэст нь","hsk_level":3},
{"word":"作业","pinyin":"zuòyè","definition":"гэрийн даалгавар","en":"гэрийн даалгавар","hsk_level":3}];
